### ISSUE TITLE
Cannot access to arata-nvm.me

### ISSUE THREAD

**Issue by ny-a** [arata-nvm/arata-nvm.github.io#109]
I think [https://arata-nvm.tech/blog](https://arata-nvm.tech/blog) is correct.

https://github.com/arata-nvm/arata-nvm.github.io/blob/54e349cf9d078306d515a2259302afe482fff6a1/src/App.svelte#L68

**Comment by arata-nvm** [comment]
Thanks for reporting! This was fixed in 4ca101b.
